let mots8Lettres = [
    'gendarme',
    'vignoble',
    'échalote',
    'calamité',
    'commande',
    'connecté',
    'bourbier',
    'lumineux',
    "lycéenne",
    "légèreté",
    "baignade",
    "balancer",
    "barbarie",
    "bassinet",
    "beaucoup",
    "bienfait",
    "bistouri",
    "blaireau",
    "bohémien",
    "bonhomme",
    "bricoler",
    "brocante",
    "building",
    "bucheron",
    "cafetier",
    "cagnotte",
    "calomnie",
    "caniveau",
    "canotier",
    "capitale",
    "carnaval",
    "carrosse",
    "carénage",
    "cavalier",
    "cervelle",
    "chanteur",
    "chantier",
    "cheminot",
    "chenille",
    "collègue",
    "commerce",
    "diffuser",
    "discours",
    "dorloter",
    "doublure",
    "découper",
    "délivrer",
    "dépotoir",
    "efficace",
    "embauche",
    "ensemble",
    "escabeau",
    "écumoire",
    "émetteur",
    "faisceau",
    "flexible",
    "fracture",
    "fuselage",
    "gaufrier",
    "goulotte",
    "grimpeur",
    "galérien",
    "hautbois",
    "histoire",
    "hôtelier",
    "humidité",
    "imbécile",
    "immortel",
    "incisive",
    "infidèle",
    "infliger",
    "jongleur",
    "judaïsme",
    "jardiner",
    "japonais",
    "karatéka",
    "kérosène",
    "kamikaze",
    "logement",
    "longueur",
    "ligament",
    "ligature",
    "magicien",
    "magnolia",
    "malfaçon",
    "mercredi",
    "monsieur",
    "mouchard",
    "mystique",
    "myocarde",
    "néophyte",
    "naviguer",
    "natalité",
    "nageoire",
    "oisiveté",
    "ombrelle",
    "ouistiti",
    "obstacle",
    "pancarte",
    "parabole",
    "paysanne",
    "penderie",
    "plongeur",
    "protéine",
    "punition",
    "querelle",
    "quotient",
    "revanche",
    "rivalité",
    "roulotte",
    "réclamer",
    "révérend",
    "résister",
    "sableuse",
    "solarium",
    "souvenir",
    "sénateur",
    "solution",
    "solidité",
    "serveuse",
    "terrasse",
    "torturer",
    "trottoir",
    "trimaran",
    "terrible",
    "tablette",
    "vendange",
    "vinaigre",
    "vaisseau",
    "vagabond",
    "vivarium",
    "vitamine",
    "officiel",
    "quartier",
    "qualifié",
    "lectrice",
    "labourer",
    "saladier",
    "sanction",
    "sandwich",
    "chausson",
    "limonade",
    "patinage",
    "émission",
    "médaille",
    "élection",
    "majorité",
    "religion",
    "province",
    "latitude",
    "ensemble",
    "altitude",
    "district",
    "critique",
    "empereur",
    "occasion",
    "anomalie",
    "bataille",
    "présence",
    "chapelle",
    "position",
    "football",
    "activité",
    "ceinture",
    "argument",
    "sécurité",
    "contrôle",
    "électeur",
    "exigence",
    "exposant",
    "équipier",
    "paranoïa",
    "pastille",
    "patineur",
    "pénombre",
    "zoologie",
    "zodiaque",
    "illusion",
    "hérisson",
    "identité",
    "hexagone",
    "humanité",
    "homicide"



















  ];

  export default mots8Lettres;