const mots = ["ORANGE", "BANANE", "POIRE", "CERISE", "MELON", "POMME", "PRUNE", "PECHE", "CITRON",   "CHIEN",
"ARBRE",
"SOLEIL",
"MAISON",
"VOITURE",
"TABLE",
"ORDINATEUR",
"LIVRE",
"FLEUR",
"MONTAGNE",
"RIVIERE",
"PLUIE",
"NEIGE",
"ETOILE",
"NUAGE",
"JARDIN",
"HORLOGE",
"BATEAU",
"FRAISE",
"POISSON",
"TIGRE",
"ELEPHANT",
"CHEVAL",
"OISEAU",
"SINGE",
"SERPENT",
"MERCI"];
const lettresFrequentes = [
    "E", "S", "A", "I", "T", "N", "R", "U", "L", "O", "D", "C", "P", "M", "V", "Q", "F", "B", "G", "H", "J" ];
export {mots, lettresFrequentes}